# Generated by Django 5.0.7 on 2024-07-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('company_reference_number', models.CharField(max_length=100)),
                ('order_status', models.CharField(max_length=50)),
            ],
        ),
    ]
