# Generated by Django 5.0.7 on 2024-07-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='options',
            field=models.JSONField(default=dict),
        ),
    ]
