# Generated by Django 5.0.7 on 2024-07-22 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_commandelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandelog',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Application.commande'),
        ),
    ]
