# Generated by Django 5.0.7 on 2024-07-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_remove_commande_designations_remove_commande_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='order_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='option',
            name='format',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='option',
            name='paper_type',
            field=models.CharField(max_length=255),
        ),
    ]
