# Generated by Django 5.0.7 on 2024-07-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_alter_option_format_alter_option_option_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='designations_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='commande',
            name='options_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='commande',
            name='order_status',
            field=models.CharField(max_length=50),
        ),
    ]
