# Generated by Django 5.0.7 on 2024-07-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_commande_adresse_commande_email_commande_fax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='id',
        ),
        migrations.AlterField(
            model_name='commande',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
