# Generated by Django 5.0.7 on 2024-07-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_remove_commande_id_alter_commande_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='order_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('devis', 'Devis'), ('facture', 'Facture'), ('bon_livraison', 'Bon de Livraison'), ('situation_client', 'Situation Client')], max_length=50),
        ),
    ]
