# Generated by Django 5.0.7 on 2024-07-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_option_unit_price_alter_commande_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
