# Generated by Django 5.0.7 on 2024-07-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_remove_option_total_price_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='tva_20',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
