# Generated by Django 5.0.7 on 2024-07-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0016_commande_total_ht_commande_total_ttc_commande_tva_20'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='total_ht',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='total_ttc',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='tva_20',
        ),
        migrations.AddField(
            model_name='option',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='option',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='option',
            name='tva_20',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
