# Generated by Django 5.0.7 on 2024-07-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0017_remove_commande_total_ht_remove_commande_total_ttc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='bc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_bc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='facture_numero',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='facture_status',
            field=models.CharField(choices=[('no_facture', 'Pas de Facture'), ('facture_termine', 'Facture Terminée')], default='no_facture', max_length=50),
        ),
        migrations.AddField(
            model_name='commande',
            name='remarque',
            field=models.CharField(blank=True, choices=[('paye', 'Payé'), ('non_paye', 'Non Payé')], max_length=50, null=True),
        ),
    ]
