# Generated by Django 5.0.7 on 2024-07-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0019_remove_commande_designations_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client_ref',
            field=models.CharField(default='', max_length=100),
        ),
    ]
