# Generated by Django 5.0.7 on 2024-07-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0020_commande_client_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='remarque',
            field=models.CharField(choices=[('paye', 'Payé'), ('non_paye', 'Non Payé')], default='non_paye', max_length=50),
        ),
    ]
