# Generated by Django 5.0.7 on 2024-07-31 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0022_remove_commande_client_ref_commande_date_facture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_facture',
        ),
    ]
