# Generated by Django 5.0.7 on 2024-08-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0023_remove_commande_date_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='designations_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='commande',
            name='options_data',
            field=models.JSONField(default=dict),
        ),
    ]
