# Generated by Django 5.0.7 on 2024-08-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0024_commande_designations_data_commande_options_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='remarque',
        ),
    ]
