# Generated by Django 5.0.7 on 2024-08-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0026_commande_remarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='grammage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='recto_verso',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('RV', 'R/V')], max_length=2, null=True),
        ),
    ]
