# Generated by Django 5.0.7 on 2024-08-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0027_option_grammage_option_recto_verso'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='devis_numero',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='devis_status',
            field=models.CharField(choices=[('no_devis', 'Pas de Devis'), ('devis_termine', 'Devis Terminé')], default='pas de devis', max_length=50),
        ),
    ]
