# Generated by Django 5.0.7 on 2024-08-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0028_commande_devis_numero_commande_devis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='bl_numero',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='bl_status',
            field=models.CharField(choices=[('no_bl', 'Pas de bon_livraison'), ('bl_termine', 'bon_livraison Terminé')], default='pas de bon_livraison', max_length=50),
        ),
    ]
