# Generated by Django 5.0.7 on 2024-08-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0029_commande_bl_numero_commande_bl_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='paper_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
