# Generated by Django 5.0.7 on 2024-08-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0031_option_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='collage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='cousu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='pelliculage_brillant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='pelliculage_mat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='piquage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='spiral',
            field=models.BooleanField(default=False),
        ),
    ]
