# Generated by Django 5.0.7 on 2024-08-03 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0032_option_collage_option_cousu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_numero', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bl_status', models.CharField(choices=[('no_bl', 'Pas de bon_livraison'), ('bl_termine', 'Bon de Livraison Terminé')], default='pas de bon_livraison', max_length=50)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bon_livraison', to='Application.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devis_numero', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('devis_status', models.CharField(choices=[('no_devis', 'Pas de Devis'), ('devis_termine', 'Devis Terminé')], default='pas de devis', max_length=50)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='Application.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture_numero', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('facture_status', models.CharField(choices=[('no_facture', 'Pas de Facture'), ('facture_termine', 'Facture Terminée')], default='pas de facture', max_length=50)),
                ('remarque', models.CharField(choices=[('paye', 'Payé'), ('non_paye', 'Non Payé')], default='non payé', max_length=50)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='Application.commande')),
            ],
        ),
    ]
