# Generated by Django 5.0.7 on 2024-08-03 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0033_bonlivraison_devis_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonlivraison',
            name='bl_status',
        ),
        migrations.RemoveField(
            model_name='bonlivraison',
            name='total_ttc',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='devis_status',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='total_ttc',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='facture_status',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='remarque',
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='bl_numero',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bon_livraison', to='Application.commande'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='Application.commande'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='devis_numero',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='Application.commande'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_numero',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
