# Generated by Django 5.0.7 on 2024-08-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0034_remove_bonlivraison_bl_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='commande',
        ),
        migrations.DeleteModel(
            name='BonLivraison',
        ),
        migrations.DeleteModel(
            name='Devis',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
