# Generated by Django 5.0.7 on 2024-08-04 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0035_remove_devis_commande_remove_facture_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='Application.commande'),
        ),
        migrations.AlterField(
            model_name='option',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='Application.designation'),
        ),
    ]
