# Generated by Django 5.0.7 on 2024-08-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0038_alter_commande_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='bl_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='devis_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='facture_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
