# Generated by Django 5.0.7 on 2024-08-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0039_commande_bl_date_commande_devis_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
