# Generated by Django 5.0.7 on 2024-08-04 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0040_commande_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='bl_date',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='bl_numero',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='bl_status',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='designations_data',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='devis_date',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='devis_numero',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='devis_status',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='facture_date',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='facture_numero',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='facture_status',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='options_data',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='remarque',
        ),
        migrations.AlterField(
            model_name='commande',
            name='order_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], max_length=50),
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_numero', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('bl_status', models.CharField(choices=[('no_bl', 'Pas de bon_livraison'), ('bl_termine', 'bon_livraison Terminé')], default='pas de bon_livraison', max_length=50)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bon_livraison', to='Application.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devis_numero', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('devis_status', models.CharField(choices=[('no_devis', 'Pas de Devis'), ('devis_termine', 'Devis Terminé')], default='pas de devis', max_length=50)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='Application.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture_numero', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('facture_status', models.CharField(choices=[('no_facture', 'Pas de Facture'), ('facture_termine', 'Facture Terminée')], default='pas de facture', max_length=50)),
                ('remarque', models.CharField(choices=[('paye', 'Payé'), ('non_paye', 'Non Payé')], default='non payé', max_length=50)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='Application.commande')),
            ],
        ),
    ]
