# Generated by Django 5.0.7 on 2024-08-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0042_bonlivraison_bl_date_devis_devis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='Application.commande'),
        ),
    ]
