# Generated by Django 5.0.7 on 2024-08-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0043_alter_designation_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonlivraison',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bon_livraison', to='Application.commande'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='order_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='designation',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='Application.commande'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='Application.commande'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='Application.commande'),
        ),
    ]
