# Generated by Django 5.0.7 on 2024-08-04 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0045_alter_bonlivraison_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonlivraison',
            name='commande',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bon_livraison', to='Application.commande'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designation',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='Application.commande'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='Application.commande'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='commande',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='Application.commande'),
            preserve_default=False,
        ),
    ]
