# Generated by Django 5.0.7 on 2024-08-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0048_populate_commande_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='devis_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='devis_status',
            field=models.CharField(default='pas de devis', max_length=50),
        ),
    ]
