# Generated by Django 5.0.7 on 2024-08-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0050_commande_devis_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='bl_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='bl_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='bl_status',
            field=models.CharField(default='pas de devis', max_length=50),
        ),
        migrations.AddField(
            model_name='commande',
            name='facture_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='facture_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='facture_status',
            field=models.CharField(default='pas de devis', max_length=50),
        ),
    ]
