# Generated by Django 5.0.7 on 2024-08-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0051_commande_bl_date_commande_bl_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='bl_status',
            field=models.CharField(default='pas de bon_livraison', max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='facture_status',
            field=models.CharField(default='pas de facture', max_length=50),
        ),
    ]
