# Generated by Django 5.0.7 on 2024-08-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0052_alter_commande_bl_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='remarque',
            field=models.CharField(choices=[('paye', 'Payé'), ('non_paye', 'Non Payé')], default='non payé', max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='bl_status',
            field=models.CharField(choices=[('no_bl', 'Pas de bon_livraison'), ('bl_termine', 'bon_livraison Terminé')], default='pas de bon_livraison', max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='devis_status',
            field=models.CharField(choices=[('no_devis', 'Pas de Devis'), ('devis_termine', 'Devis Terminé')], default='pas de devis', max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='facture_status',
            field=models.CharField(choices=[('no_facture', 'Pas de Facture'), ('facture_termine', 'Facture Terminée')], default='pas de facture', max_length=50),
        ),
    ]
