# Generated by Django 5.0.7 on 2024-08-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0053_commande_remarque_alter_commande_bl_status_and_more'),
        ('Application', '0053_logentry_delete_commandelog'),
    ]

    operations = [
    ]
