# Generated by Django 5.0.7 on 2024-08-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0056_alter_logentry_bon_livraison_alter_logentry_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
